# Generated by Django 3.2.19 on 2023-08-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('RegistrationId', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('registrationNumber', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('srmmail', models.EmailField(max_length=100)),
                ('personalmail', models.EmailField(max_length=100)),
                ('mobile', models.IntegerField(max_length=15)),
                ('whatsappnumber', models.IntegerField(max_length=15)),
                ('year', models.IntegerField(verbose_name=1)),
                ('domain1', models.CharField(max_length=100)),
                ('domain2', models.CharField(max_length=100)),
                ('linkedin', models.URLField(max_length=300)),
                ('github', models.URLField(max_length=300)),
                ('resume', models.URLField(max_length=300)),
                ('question1', models.TextField(max_length=1000)),
                ('question2', models.TextField(max_length=1000)),
            ],
        ),
    ]
