# Generated by Django 3.2.19 on 2023-08-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitmentForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='whatsappnumber',
            field=models.IntegerField(),
        ),
    ]
